### ISSUE TITLE
Status is always IN_PROGRESS

### ISSUE THREAD

**Issue by DutchKevv** [toko-bifrost/ms-teams-deploy-card#22]
Hi there,

Great work on the plugin, it looks really good!

I tried setting it up yesterday and all works fine, except status always keeps hanging on IN_PROGRESS for me.

`jobs:
  build:
    name: Build, push && deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.5.0
    steps:

### CHECKOUT
      - name: Checkout repository
        uses: actions/checkout@v2

### MS TEAMS
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          show-on-failure: true

### NODEJS
      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

### CLIENT
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-client-public-web-node-modules
        env:
          cache-name: cache-client-public-web-node-modules
        with:
          path: ./node_modules
          key: client-public-web-${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      - name: install client dependencies
        working-directory: frontend
        run: npm install --production=false --no-progress --no-audit --no-fund
      - name: build client
        working-directory: frontend
        run: npm run build

### SERVER

      - name: Build image and push to registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry:  docker.pkg.github.com
          image_name: server-public
          build_extra_args: "--build-arg NODE_ENV=production"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_IP }}
          username: ${{ secrets.DEVELOPMENT_SSH_USERNAME }}
          password: ${{ secrets.DEVELOPMENT_SSH_PASSWORD }}
          command_timeout: 10m
          script: |
            cd /home/kewin/Projects/sphingx/client-public-web
            echo ${{ secrets.GITHUB_TOKEN }} | docker login --username=${{ github.actor }} --password-stdin docker.pkg.github.com
            docker pull docker.pkg.github.com/sphingx/client-public-web/server-public:latest
            docker kill server-public
            CONFIG=production docker-compose -f ./docker-compose.yml -f ./docker-compose.prod.yml up -d
`

![image](https://user-images.githubusercontent.com/5072775/86768666-36f17f80-c04e-11ea-9c7e-b5961e9bb468.png)

It doesn't seem to update the status to SUCCESS or FAILURE, so guess i;m doing something wrong.

Any advice?

Thanks!

**Comment by femrtnz** [comment]
I'm facing similar issue here as well, even on my simple test as you can see below:

```
jobs:
  cypress-run:
    runs-on: macos-latest
    name: testing ms-teams-deploy-card status
     steps:
        - name: Test la execution
          run: exit 1

        - name: Notify pipeline alerts channel
          uses: toko-bifrost/ms-teams-deploy-card@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            webhook-uri: ${{ secrets.TEST_TEAMS_WEBHOOK }}
            card-layout-start: cozy
            card-layout-exit: cozy
            show-on-start: false
            show-on-exit: false
            show-on-failure: true
          if: failure()
```
