### ISSUE TITLE
Show Card on Failure is resulting in a card for skipped jobs

### ISSUE THREAD

**Issue by dakota-maker-by** [toko-bifrost/ms-teams-deploy-card#27]
Hi there,

My team has been using this library now for a little bit and the cards have been working great, but we are getting some unexpected behavior from the `show-on-failure` property, which is showing cards when the job has skipped. I definitely get the idea behind skipped not being success, but given the name I think show-on-failure should only show for failed builds

![Screen Shot 2020-07-27 at 9 37 03 AM](https://user-images.githubusercontent.com/28930322/88555247-28630c00-cfed-11ea-8000-7ea49ecf83da.png)

setup:

```
- name: Publish Automerge Failure Card
  uses: toko-bifrost/ms-teams-deploy-card@3.1.2
  if: always()
  with:
      github-token: ${{ secrets.pat }}
      webhook-uri: ${{ secrets.uri }}
      show-on-start: false
      show-on-failure: true
```
