### ISSUE TITLE
Only seeing "in progress" when running within a matrix 

### ISSUE THREAD

**Issue by dakota-maker-by** [toko-bifrost/ms-teams-deploy-card#33]
Hi there,

I am trying to run this action within a workflow that relies on matracies:

```
  deploy:
    runs-on: ubuntu-latest
    needs: build-deployment-envs
    strategy:
      matrix: ${{ fromJson(needs.build-deployment-envs.outputs.matrix) }}
    
   ...

      - name: Check for failure and set card layout
        if: failure()
        run: echo "CARD_LAYOUT=complete" >> $GITHUB_ENV

      - name: Publish Deployment Card
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ webhook URL secret name }}
          environment: ${{ matrix.env }}
          show-on-start: false
          show-on-exit: true
          card-layout-exit: ${{ env.CARD_LAYOUT }}
          view-status-action-text: "View status (${{ matrix.mfeName }})"
```

but regardless of how the run is going, we are only seeing "In Progress". I made sure to not have job names in place, so I know the known issue #5 is not impacting this, but the next culprit seems to be running within a matrix. Not sure if there was any insight on this but I wanted to report it for visibility if nothing else.

**Comment by mombe090** [comment]
Hey i have the same issue

**Comment by aldwyn-acn** [comment]
Hey guys, I will look into this.

**Comment by diego-zoo** [comment]
Have the same issue.

**Comment by mshirman** [comment]
Same here. The completion status is always IN-PROGRESS

**Comment by dmbarry86** [comment]
Same here. Any update on this since December?

**Comment by marcosmesser** [comment]
I am using a work around for this issue, might be useful for someone else.
```yaml
  notification-job:
    runs-on: ubuntu-latest
    needs: [job-with-matrix]
    if:  "always() && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2

      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          card-layout-exit: complete
          show-on-start: false

      - name: Build matrix failed
        if: ${{ needs.job-with-matrix.result != 'success' }}
        run: exit 1

      - name: Build matrix succeeded
        if: ${{ needs.job-with-matrix.result == 'success' }}
        run: echo "Targets built and deployed"
```
The notification won't have the actual error, but it will at least have the right status for the whole workflow.
