### ISSUE TITLE
Exit status sometimes wrong

### ISSUE THREAD

**Issue by abivolmv** [toko-bifrost/ms-teams-deploy-card#34]
Hi,
sometimes the action fails but in teams we get status successful. Sometimes it is correct - Failure.

![image](https://user-images.githubusercontent.com/39116856/105189229-09c17600-5b35-11eb-8b87-480592284051.png)

```
...
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-18.04

    steps:
    
      - uses: actions/checkout@v2
      
      - name: Notify Teams channel
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          webhook-uri: ${{ secrets.MSO_TEAMS_FERRARI_WEBHOOK_URI }}
          github-token: ${{ github.token }}
          environment: Dev
...
```

We also use the bobheadxi/deployments@v0.4.2 action, in case it is needed to be known.

We don't use matrix so it is different, I guess, from #33 .
