### ISSUE TITLE
Error in the post notify teams channel run

### ISSUE THREAD

**Issue by abivolmv** [toko-bifrost/ms-teams-deploy-card#35]
We get this error in the post notify teams channel run:
```
(node:3227) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of null
    at Object.formatCompactLayout (/home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/3.1.2/dist/post/index.js:1:236544)
    at Object.formatAndNotify (/home/runner/work/_actions/toko-bifrost/ms-teams-deploy-card/3.1.2/dist/post/index.js:1:37551)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
runs-on: ubuntu-18.04
    steps:
      - name: Notify Teams channel
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          webhook-uri: ${{ secrets.MSO_TEAMS_WEBHOOK_URI }}
          github-token: ${{ github.token }}
          environment: ${{github.event.inputs.env}}
          show-on-start: false
```
